# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Continuous Integration

on:
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    strategy:
      matrix:
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
        server-id: github-javafx-osgi
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    - name: Build with Maven
      run: mvn verify
      env:
        GITHUB_TOKEN: ${{ github.token }}
        MAVEN_USERNAME: tschie
        MAVEN_PASSWORD: ${{ github.token }}
    - uses: actions/upload-artifact@v2
      name: Upload Artifact
      with:
        name: ${{ matrix.platform }}-binary
        path: workench/target/*Workbench*
